# Introdução

## Histórico deste livro

Este livro foi estruturado a partir da apostila elaborada pelos pesquisadores Diogo B. Provete, Fernando R. da Silva e Thiago Gonçalves-Souza para ministrar o curso *Estatística aplicada à ecologia usando o R* no PPG em Biologia Animal da UNESP de S.J. Rio Preto em abril de 2011. Os três pesquisadores eram alunos do PPG em Biologia Animal quando elaboraram o material disponibilizado na apostila. A proposta de transformar a apostila em livro era um tópico recorrente desde 2011, e concretizada 10 anos depois. Neste período, Diogo, Fernando e Thiago foram contratados pela Universidade Federal de Mato Grosso do Sul, Universidade Federal de São Carlos, campus Sorocaba e Universidade Federal Rural de Pernambuco, respectivamente. Nestes anos eles ofertaram diferentes versões do curso *Estatística aplicada à ecologia usando o R* para alunos de graduação e pós graduação em diferentes instituições do Brasil. A possibilidade da oferta destes novos cursos fortaleceu a ideia de trasformar a apostila em um livro com base nas experiências em sala de aula. Considerando que novas abordagens ecológicas vem sendo descritas a uma taxa elevada nos últimos anos, era de se esperar que as informações disponíveis na apostila estivessem defasadas após 10 anos. Por este motivo, Diogo, Fernando e Thiago resolveram convidar outros dois pesquisadores, Gustavo B. Paterno da Universität München e Maurício H. Vancine do PPG em Zoologia da UNESP, campus Rio Claro , que são referências no uso de estatística em ecologia usando o R. Com o time completo, passamos mais de um ano realizando reuniões, compartilhando scripts e pagando cerveja para os co-autores por capítulo atrasado até chegarmos neste primeira versão do livro.

## Objetivo deste livro

Nossa proposta com este livro é de traçar o melhor caminho (pelo menos em nosso ponto de vista) entre questões ecológicas e os métodos estatísticos mais robustos para testá-las. Guiar seus passos nesse caminho (nem sempre linear) necessita que você utilize um requisito básico: o de utilizar seu esforço para caminhar. O nosso esforço, em contrapartida, será o de indicar as melhores direções para que você adquira certa independência em análises ecológicas. Um dos nossos objetivos é mostrar que o conhecimento de teorias ecológicas e a utilização de questões apropriadas são o primeiro passo na caminhada rumo à compreensão da lógica estatística. Não deixe que a estatística se torne a "pedra no seu caminho". Em nossa opinião, programas com ambiente de programação favorecem o entendimento da lógica estatística, uma vez que cada passo (lembre-se de que você está caminhado em uma estrada desconhecida) precisa ser coordenado, ou seja, as linhas de comando (detalhes abaixo) precisam ser compreendidas para que você teste suas hipóteses.

A primeira parte deste livro pretende utilizar uma estratégia que facilita a escolha do teste estatístico apropriado, por meio da seleção de questões/hipóteses claras e da ligação dessas hipóteses com a teoria e o método (veja esquema no Capítulo 2). Enfatizamos que é sempre bom ter em mente que é muito importante saber aonde se quer chegar para poder escolher o que fazer. Posteriormente à escolha de suas questões é necessário transferir o contexto ecológico para um contexto meramente estatístico (hipótese nula/alternativa). A partir da definição de sua hipótese nula partiremos para a aplicação de cada teste estatístico (de modelos lineares generalizados à análises multivariadas) utilizando como plataforma o programa R. Antes de detalhar cada análise estatística, apresentaremos os comandos básicos para a utilização do R e os tipos de distribuição estatística que são essenciais para a compreensão dos testes estatísticos. Para isso, organizamos um esquema que chamamos de "estrutura lógica" que facilita a compreensão dos passos necessários para testar suas hipóteses (veja esquema no Capítulo 2).

## O que você não encontrará neste livro

Aprofundamento teórico, detalhes matemáticos, e explicação dos algoritmos são informações que infelizmente não serão abordadas neste livro. O foco do livro é a explicação de como cada teste funciona (teoria e procedimentos matemáticos básicos) e sua aplicação em testes ecológicos usando o programa R. Para tanto, o livro dos irmãos Pierre e Louis Legendre (Legendre & Legendre 2012) é uma leitura que permite o aprofundamento de cada uma das análises propostas aqui. Além disso, são de fundamental importância para o amadurecimento em análises ecológicas as seguintes leituras: Manly (1991), Pinheiro & Bates (2000), Scheiner & Gurevitch (2001), Quinn & Keough (2002), Venables & Ripley (2002), Magurran (2011), Gotelli & Ellison (2010) e Zar (2009).

## Por que usar o R? 

Os criadores do R o chamam de uma linguagem e ambiente de programação estatística e gráfica. A linguagem R também é chamada de programação "orientada ao objeto" (*object oriented programming*), o que significa que utilizar o R envolve basicamente a criação e manipulação de objetos em uma tela branca em que o usuário tem de dizer exatamente o que deseja que o programa execute ao invés de simplesmente pressionar um botão. E vem daí uma das grandes vantagens em se usar o R: o usuário tem total controle sobre o que está acontecendo e também tem de compreender o que deseja antes de executar uma análise. Além disso, o R permite integração com outros programas escritos em C++, Python e Java permitindo que os usuários possam aplicar novas metodologias sem ter que aprender novas linguagens.

Na página pessoal do Prof. Nicolas J. Gotelli (<http://www.uvm.edu/~ngotelli/homepage.html>) existem vários conselhos para um estudante iniciante de ecologia. Dentre esses conselhos, o Prof. Gotelli menciona que o domínio de uma linguagem de programação é uma das habilidades mais importantes, porque dá liberdade ao ecólogo para executar tarefas que vão além daquelas disponíveis em pacotes comerciais. Além disso, a maioria das novas análises propostas nos mais reconhecidos periódicos em ecologia normalmente são implementadas em linguagem R, e os autores incluem normalmente o código fonte no material suplementar dos artigos, tornando a análise acessível. A partir do momento que essas análises ficam disponíveis (seja por código fornecido pelo autor ou por implementação em pacotes pré-existentes), é mais simples entendermos a lógicas de análises complexas, especialmente as multivariadas, com nossos próprios dados realizando-as passo a passo. Sem a utilização do R, normalmente temos que contatar os autores que nem sempre são acessíveis.

Uma última vantagem é que por ser um software livre, a citação do R em artigos é permitida e até aconselhável. Para saber como citar o R, digite `citation()` na linha de comando. Para citar um pacote específico, digite `citation()` com o nome do pacote entre aspas dentro dos parênteses. Neste ponto, esperamos ter convencido você leitor de que aprender a utilizar o R tem inúmeras vantágens, vai ser difícil no começo mas continue e perceberá que o investimento vai valer à pena no futuro.

## Como usar este livro

Os conteúdo apresentado em cada capítulo são independentes entre si. Portanto, você pode utilizar este livro de duas formas. A primeira é seguir uma ordem sequencial (capítulos 1, 2, 3, ...) que recomendamos, principalmente, para as pessoas que não possuem familiaridade com a programação em R. A segunda é selecionar o capítulo que contém a análise de seu interesse e mudar de um capítulo para outro sem seguir a sequencia apresentada no livro.

Com exceção dos capítulos 2 e 3, os outros capítulos foram elaborados seguindo a mesma estrutura contendo uma descrição da análise estatística (*background*) e exemplos relacionados com questões ecólogicas que podem ser respondidas por está análise. Todos as informações e dados dos exemplos utilizados neste livro estão armazenados no pacote *ecodados*. Assim, recomendamos que você carregue este pacote, no início de cada capítulo, para ter acesso aos dados necessários para realizar os comandos no R. Todos os exemplos são compostos por: i) uma descrição dos dados utilizados, ii) pergunta e predição do trabalho, iii) descrição das variáveis resposta(s) e preditora(s), e iv) descrição e explicação das linhas de comando do R necessárias para realização da análises. Os exemplos utilizados são baseados em dados reais que já foram publicados em artigos científicos ou são dados coletados por um dos autores deste livro. Nós recomendamos que primeiro você utilize estes exemplos para se familiarizar com análises e a formatação das linhas e colunas das planilhas. Em seguida, utilize os seus dados para realizar as análises. Esta é a melhor maneira para se familiarizar com as linhas de comando do R. 

Muitas das métricas ou índices apresentados no livro não foram traduzidas para o português porque seus acrônimos são clássicos e bem estabelecidos na literatura. Nestes casos, consideramos que a tradução poderia confundir as pessoas que estão começando a se familiarizar com a literatura específica. Realçamos que não estamos abordando todas as possibilidades disponíveis e existem outros pacotes e funções no R que realizam as mesmas análises. Contudo, esperamos que o conteúdo apresentado permita que os leitores adquiram independência e possam caminhar sozinhos na exploração de novos pacotes e funções para responderem suas perguntas biológicas.
